Delegator rewards
figment-networks/cosmos-worker pull request #17
Opened 2021-02-25 13:52 UTC by eesmerdag

@pacmessica as i had seen grpc endpoint is not available. so the same way as it was implemented for cosmos-3.

2021-02-25 13:54 UTC, eesmerdag commented on test/integration/api_test.go
> +				Height:  5217493,
5217492 is the height where GetRewards happens.  and for that height datahub returns null for rewards. It is same for every block where GerReward happens. is this a bug, or this is how it should work? @pacmessica

2021-02-25 15:34 UTC, eesmerdag commented
https://www.notion.so/figmentnetworks/Add-reward-handler-in-cosmos-4-worker-2759ce2c6d7b4a398fee707a7ea98c26

2021-03-01 14:35 UTC, pacmessica requested changes

2021-03-01 14:35 UTC, pacmessica commented on cmd/worker-cosmos/mainn.go
> +package main
what is this file?

2021-03-01 14:35 UTC, pacmessica commented on test/integration/api_test.go
> +	dataHubKey := "" // set your api key before testing
if we decide to add a testing step to github ci, then this won't work. I think we can set these values in a github secret config or something, @lukanus thoughts?

2021-03-01 14:35 UTC, pacmessica commented on test/integration/api_test.go
> +				Height:  5217493,
In cosmos, you need to claim rewards. The rewards you see at `/distribution/delegators/:addr` are rewards that you've earned, but haven't claimed yet. So if you look at the rewards balance for height `5217491`, it's 
```
        "total": [
            {
                "denom": "uatom",
                "amount": "13181.963916473909410000"
            }
        ]
 ```

Then at height `5217492`, they claimed the `0.013182ATOM`[mintscan](https://www.mintscan.io/cosmos/txs/0904FC6170233A9FEB9031CBF76EBE8B3A57CC00594052D706613A58C3693C1E). The height where you claim rewards will always be null- this is how it should work.

2021-03-01 14:35 UTC, pacmessica commented on test/integration/api_test.go
> +				require.Equal(t, resp.Rewards[0].Text, tt.resultText)
can you check the other values (exp, currency, numeric)

2021-03-01 15:13 UTC, eesmerdag commented on cmd/worker-cosmos/mainn.go
> +package main
😋

2021-03-01 15:14 UTC, eesmerdag commented on test/integration/api_test.go
> +	dataHubKey := "" // set your api key before testing
i believe we could create a new test user for this key in such a case. i saw this approach before,

2021-03-01 15:44 UTC, eesmerdag commented on api/client.go
>  	rateLimiter *rate.Limiter
👍

2021-03-01 16:35 UTC, lukanus commented on test/integration/api_test.go
> +	dataHubKey := "" // set your api key before testing
I suppose if we used regular config instead of this, we should be able to pass both as env param. 
However I'm not sure should we add any integration tests to github.  
Especially if this would bound  our releaseability to datahub state.

2021-03-01 17:20 UTC, pacmessica commented on cmd/worker-cosmos/config/config.go
> +	CosmosLCDAddr  string `json:"cosmos_lcd_addr" envconfig:"COSMOS_LCD_ADDR"`
this is definitely better naming, so 👍 . however provisioning expects `tendermint_lcd_addr` as a key, so I would leave the json and envconfig the same because it's extra work since we would need to change it for cosmos-3 too.  Does that make sense? 

https://github.com/figment-networks/provisioning/blob/a202e7f9fc4fa0f689202fac968c6bded61178c7/playbooks/roles/sub/apps/datahub/dh_worker_cosmoslike/defaults/main.yml#L31

2021-03-01 18:06 UTC, pacmessica approved these changes
lgtm

2021-03-01 18:10 UTC, merged